apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: helm-guestbook-appset
  namespace: argocd

spec:
  goTemplate: true

  generators:
    - git:
        repoURL: https://github.com/shareq67/argocd-example-apps.git
        revision: master
        directories:
          - path: envs/*

  template:
    metadata:
      name: 'helm-guestbook-{{path.basename}}'

    spec:
      project: poc-demo

      source:
        repoURL: https://github.com/shareq67/argocd-example-apps.git
        targetRevision: master
        path: helm-guestbook

        helm:
          valueFiles:
            - '{{path.path}}/values.yaml'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-guestbook'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true